import { spawnSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { type DeployTarget, applyDeployConfig } from './deploy.js';
import { log } from './logger.js';
import { STACK } from './stack.js';

export interface ScaffoldOptions {
  deployTarget?: DeployTarget;
}

export interface ScaffoldResult {
  ok: boolean;
  dir: string;
  error?: string;
  existingFiles?: string[];
}

export function scaffold(targetDir: string, opts: ScaffoldOptions = {}): ScaffoldResult {
  const dir = path.resolve(targetDir);

  if (fs.existsSync(dir)) {
    const entries = fs.readdirSync(dir);
    if (entries.length > 0) {
      return {
        ok: false,
        dir,
        error: `Directory ${dir} is not empty — refusing to scaffold.`,
        existingFiles: entries,
      };
    }
  } else {
    fs.mkdirSync(dir, { recursive: true });
  }

  log.step(`Scaffolding SvelteKit project at ${dir}`);

  writeFiles(dir);

  if (opts.deployTarget) {
    applyDeployConfig(dir, opts.deployTarget);
  }

  log.info('Running npm install (this can take a minute)…');
  const npm = spawnSync('npm', ['install', '--no-audit', '--no-fund'], {
    cwd: dir,
    stdio: 'inherit',
  });
  if (npm.status !== 0) {
    return { ok: false, dir, error: 'npm install failed. See output above.' };
  }

  log.info('Running svelte-kit sync (generates .svelte-kit/tsconfig.json)');
  const sync = spawnSync('npx', ['svelte-kit', 'sync'], { cwd: dir, stdio: 'inherit' });
  if (sync.status !== 0) {
    log.warn('svelte-kit sync returned non-zero — the first verify run will retry it.');
  }

  log.info('Initialising git repo');
  const gitInit = spawnSync('git', ['init', '-q'], { cwd: dir, stdio: 'inherit' });
  if (gitInit.status === 0) {
    spawnSync('git', ['add', '.'], { cwd: dir, stdio: 'ignore' });
    spawnSync('git', ['commit', '-q', '-m', 'svelte-mate: initial scaffold'], {
      cwd: dir,
      stdio: 'ignore',
    });
  }

  log.ok('Scaffold complete');
  return { ok: true, dir };
}

function writeFiles(dir: string): void {
  const files: Record<string, string> = {
    'package.json': packageJson(path.basename(dir)),
    'svelte.config.js': svelteConfig(),
    'vite.config.ts': viteConfig(),
    'tsconfig.json': tsconfig(),
    'biome.json': biomeConfig(),
    '.prettierrc.json': prettierConfig(),
    '.prettierignore': prettierIgnore(),
    '.gitignore': gitignore(),
    'src/app.html': appHtml(),
    'src/app.css': appCss(),
    'src/app.d.ts': appDts(),
    'src/routes/+layout.svelte': rootLayout(),
    'src/routes/+page.svelte': indexPage(),
    'static/favicon.svg': favicon(),
    'README.md': `# ${path.basename(dir)}\n\nGenerated by svelte-mate. Stack: SvelteKit ${STACK.sveltekit}, Svelte ${STACK.svelte}, Tailwind ${STACK.tailwind}, Biome (\`.ts\`/\`.js\`/\`.json\`), Prettier + prettier-plugin-svelte (\`.svelte\`), TypeScript strict.\n\n## Dev\n\n\`\`\`bash\nnpm run dev        # dev server\nnpm run build      # production build\nnpm run preview    # preview production build\nnpm run check      # svelte-check + biome check + prettier check\n\`\`\`\n`,
  };

  for (const [rel, content] of Object.entries(files)) {
    const full = path.join(dir, rel);
    fs.mkdirSync(path.dirname(full), { recursive: true });
    fs.writeFileSync(full, content, 'utf-8');
  }
}

function packageJson(name: string): string {
  return `${JSON.stringify(
    {
      name,
      type: 'module',
      version: '0.0.1',
      private: true,
      scripts: {
        dev: 'vite dev',
        build: 'vite build',
        preview: 'vite preview',
        prepare: 'svelte-kit sync',
        'svelte:check': 'svelte-kit sync && svelte-check --tsconfig ./tsconfig.json',
        'svelte:check:watch': 'svelte-kit sync && svelte-check --tsconfig ./tsconfig.json --watch',
        'biome:check': 'biome check src/',
        'biome:fix': 'biome check --write src/',
        'prettier:check': 'prettier --check "**/*.svelte"',
        'prettier:fix': 'prettier --write "**/*.svelte"',
        check:
          'svelte-kit sync && svelte-check --tsconfig ./tsconfig.json && biome check src/ && prettier --check "**/*.svelte"',
      },
      dependencies: {
        '@tailwindcss/vite': STACK.tailwind,
        tailwindcss: STACK.tailwind,
      },
      devDependencies: {
        '@biomejs/biome': STACK.biome,
        '@sveltejs/adapter-auto': STACK.adapterAuto,
        '@sveltejs/kit': STACK.sveltekit,
        '@sveltejs/vite-plugin-svelte': STACK.vitePluginSvelte,
        prettier: STACK.prettier,
        'prettier-plugin-svelte': STACK.prettierPluginSvelte,
        svelte: STACK.svelte,
        'svelte-check': STACK.svelteCheck,
        typescript: STACK.typescript,
        vite: STACK.vite,
      },
    },
    null,
    2,
  )}\n`;
}

function svelteConfig(): string {
  return `import adapter from '@sveltejs/adapter-auto';
import { vitePreprocess } from '@sveltejs/vite-plugin-svelte';

/** @type {import('@sveltejs/kit').Config} */
const config = {
  preprocess: vitePreprocess(),
  kit: {
    adapter: adapter(),
    alias: {
      '@/*': 'src/*',
    },
  },
};

export default config;
`;
}

function viteConfig(): string {
  return `import tailwindcss from '@tailwindcss/vite';
import { sveltekit } from '@sveltejs/kit/vite';
import { defineConfig } from 'vite';

export default defineConfig({
  plugins: [tailwindcss(), sveltekit()],
});
`;
}

function tsconfig(): string {
  return `${JSON.stringify(
    {
      extends: './.svelte-kit/tsconfig.json',
      compilerOptions: {
        allowJs: true,
        checkJs: true,
        esModuleInterop: true,
        forceConsistentCasingInFileNames: true,
        resolveJsonModule: true,
        skipLibCheck: true,
        sourceMap: true,
        strict: true,
        moduleResolution: 'bundler',
      },
    },
    null,
    2,
  )}\n`;
}

function biomeConfig(): string {
  return `${JSON.stringify(
    {
      $schema: 'https://biomejs.dev/schemas/1.9.4/schema.json',
      vcs: { enabled: true, clientKind: 'git', useIgnoreFile: true },
      files: {
        ignoreUnknown: true,
        ignore: ['build', '.svelte-kit', 'node_modules', 'dist', '*.svelte'],
      },
      formatter: { enabled: true, indentStyle: 'space', indentWidth: 2, lineWidth: 100 },
      linter: { enabled: true, rules: { recommended: true } },
      javascript: { formatter: { quoteStyle: 'single', semicolons: 'always' } },
    },
    null,
    2,
  )}\n`;
}

function prettierConfig(): string {
  return `${JSON.stringify(
    {
      plugins: ['prettier-plugin-svelte'],
      useTabs: false,
      tabWidth: 2,
      singleQuote: true,
      printWidth: 100,
      overrides: [{ files: '*.svelte', options: { parser: 'svelte' } }],
    },
    null,
    2,
  )}\n`;
}

function prettierIgnore(): string {
  return `node_modules/
.svelte-kit/
build/
dist/
package-lock.json
`;
}

function gitignore(): string {
  return `node_modules/
.svelte-kit/
build/
dist/

# Env
.env
.env.*
!.env.example

# Logs
npm-debug.log*
pnpm-debug.log*
yarn-debug.log*
yarn-error.log*

# svelte-mate runtime artefacts (leaked if the agent is killed mid-run)
.svelte-mate-prompt*

.DS_Store
`;
}

function appHtml(): string {
  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <link rel="icon" type="image/svg+xml" href="%sveltekit.assets%/favicon.svg" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    %sveltekit.head%
  </head>
  <body data-sveltekit-preload-data="hover" class="min-h-screen bg-white text-slate-900 antialiased dark:bg-slate-950 dark:text-slate-100">
    <div style="display: contents">%sveltekit.body%</div>
  </body>
</html>
`;
}

function appCss(): string {
  return `@import "tailwindcss";
`;
}

function appDts(): string {
  return `// See https://svelte.dev/docs/kit/types#app
// for information about these interfaces
declare global {
  namespace App {
    // interface Error {}
    // interface Locals {}
    // interface PageData {}
    // interface PageState {}
    // interface Platform {}
  }
}

export {};
`;
}

function rootLayout(): string {
  return `<script lang="ts">
  import '../app.css';

  let { children } = $props();
</script>

{@render children()}
`;
}

function indexPage(): string {
  return `<script lang="ts">
  const greeting = $state('Hello from svelte-mate');
</script>

<svelte:head>
  <title>Hello from svelte-mate</title>
</svelte:head>

<main class="mx-auto max-w-2xl px-6 py-24">
  <h1 class="text-4xl font-bold tracking-tight">{greeting}</h1>
  <p class="mt-4 text-lg text-slate-600 dark:text-slate-400">
    Edit <code class="rounded bg-slate-100 px-1.5 py-0.5 text-sm dark:bg-slate-800">src/routes/+page.svelte</code>
    to begin.
  </p>
</main>
`;
}

function favicon(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128"><rect width="128" height="128" rx="24" fill="#ff3e00"/><text x="64" y="82" text-anchor="middle" font-family="system-ui,sans-serif" font-size="64" font-weight="700" fill="#ffffff">S</text></svg>
`;
}
